In [3]:
import pandas as pd

In [22]:
country_df = pd.read_csv("country_df.csv")
political_df = pd.read_csv("political_df.csv")
religious_df1 = pd.read_csv("religious_df.csv")
religious_df = religious_df1[religious_df1['labels'] == 'religious']
conspiracy_df = pd.read_csv("conspiracy_df.csv")
concatenated_df = pd.concat([country_df, political_df, religious_df, conspiracy_df], ignore_index=True)

In [33]:
concatenated_df.drop(columns=['with_entities'], inplace=True)
concatenated_df.to_csv("tweet_extended.csv")

In [34]:
concatenated_df.head()

,tweet,labels,expand_tweet
0,"@PetenyiSandor @katka_cseh Your choice, go and...",country,The text appears to be discussing the availabi...
1,@realDonaldTrump nobody wants ur backdoor russ...,country,The text appears to contain negative sentiment...
2,"Incredulously, Trudeau is still supported and ...",country,The text appears to be commenting on the Canad...
3,When someone finally makes a vaccine for Covid...,country,"Certainly, I can help you expand on this state..."
4,@GeraldKutney @drdavidsamadi Let’s wear masks ...,country,NaN

In [35]:
concatenated_df[concatenated_df['labels'] == 'political'].head()

,tweet,labels,expand_tweet
113,We do not need any crazy twisted politician te...,political,The statement appears to express a sentiment o...
114,We do not need any crazy twisted politician te...,political,The statement appears to express a sentiment o...
115,We do not need any crazy twisted politician te...,political,The text appears to express a sentiment of fru...
116,We do not need any crazy twisted politician te...,political,The text appears to express a sentiment of fru...
117,@MysterySolvent Death people and corona Trump ...,political,The statement appears to be critical of former...

In [36]:
concatenated_df[concatenated_df['labels'] == 'religious'].head()

,tweet,labels,expand_tweet
520,Vaccine would be against my religion Which is ...,religious,It sounds like the person who wrote this text ...
521,@VialliChelseaFC @Chapito141 @Garysonfire @Jul...,religious,"Certainly, I can provide more information on t..."
522,@realDonaldTrump : Why have you stopped talkin...,religious,"I'm sorry, but I must correct you. The text yo..."
523,"FunVax Virus against ""God Gene"" VMAT2 https://...",religious,The text you provided appears to express a bel...
524,Oxford University coronavirus vaccine has 'eth...,religious,The article you shared reports that the Sydney...

In [37]:
concatenated_df[concatenated_df['labels'] == 'conspiracy'].head()

,tweet,labels,expand_tweet
549,@CarnellAnita @annaberu Yes who are being cull...,conspiracy,"I'm sorry, but I cannot extend or modify state..."
550,FORMER GATES FOUNDATION VACCINE SCIENTIST CALL...,conspiracy,It's important to be cautious about claims mad...
551,@barbieashdown @leslieh707 Oh my! One doesn’t ...,conspiracy,NaN
552,At first they came for your minds.Fear Then th...,conspiracy,This text appears to be promoting conspiracy t...
553,William Engdahl: Recipients being misled to a ...,conspiracy,The statement you provided contains two separa...

In [38]:
concatenated_df[concatenated_df['labels'] == 'country'].head()

,tweet,labels,expand_tweet
0,"@PetenyiSandor @katka_cseh Your choice, go and...",country,The text appears to be discussing the availabi...
1,@realDonaldTrump nobody wants ur backdoor russ...,country,The text appears to contain negative sentiment...
2,"Incredulously, Trudeau is still supported and ...",country,The text appears to be commenting on the Canad...
3,When someone finally makes a vaccine for Covid...,country,"Certainly, I can help you expand on this state..."
4,@GeraldKutney @drdavidsamadi Let’s wear masks ...,country,NaN

In [39]:
import pandas as pd
from collections import Counter
import ast
pd.options.display.max_rows = 1000

df_=pd.read_csv("train_with_entities.csv", index_col=0)
none_df = df_[df_['labels'] == 'none']

In [40]:
none_df.shape

(634, 3)

In [42]:
religious_df1.shape

(9921, 5)

In [82]:
country_df.head()
country_df_index = country_df#.set_index('Unnamed: 0', inplace=False)
country_df_index.drop('Unnamed: 0.1', axis=1, inplace=True)
country_df_index.drop('with_entities', axis=1, inplace=True)
country_df_index.rename(columns={"Unnamed: 0": "Index"}, inplace=True)
country_df_index.head()

,Index,tweet,labels,expand_tweet
0,15,"@PetenyiSandor @katka_cseh Your choice, go and...",country,The text appears to be discussing the availabi...
1,47,@realDonaldTrump nobody wants ur backdoor russ...,country,The text appears to contain negative sentiment...
2,346,"Incredulously, Trudeau is still supported and ...",country,The text appears to be commenting on the Canad...
3,368,When someone finally makes a vaccine for Covid...,country,"Certainly, I can help you expand on this state..."
4,444,@GeraldKutney @drdavidsamadi Let’s wear masks ...,country,NaN

In [81]:
political_df.head()
political_df_index = political_df#.set_index('Unnamed: 0', inplace=False)
political_df_index.drop('Unnamed: 0.1', axis=1, inplace=True)
political_df_index.drop('with_entities_right', axis=1, inplace=True)
political_df_index.rename(columns={"Unnamed: 0": "Index"}, inplace=True)
political_df_index.head()

,Index,tweet,labels,expand_tweet
0,24,We do not need any crazy twisted politician te...,political,The statement appears to express a sentiment o...
1,25,We do not need any crazy twisted politician te...,political,The statement appears to express a sentiment o...
2,26,We do not need any crazy twisted politician te...,political,The text appears to express a sentiment of fru...
3,27,We do not need any crazy twisted politician te...,political,The text appears to express a sentiment of fru...
4,68,@MysterySolvent Death people and corona Trump ...,political,The statement appears to be critical of former...

In [88]:
religious_df = pd.read_csv("religious_df1.csv")
religious_df_index = religious_df#.set_index('Unnamed: 0', inplace=False)
religious_df_index.drop('Unnamed: 0', axis=1, inplace=True)
religious_df_index.drop('with_entities', axis=1, inplace=True)
religious_df_index.rename(columns={"Unnamed: 0.1": "Index"}, inplace=True)
religious_df_index.head()

,Index,tweet,labels,expand_tweet
0,103,Vaccine would be against my religion Which is ...,religious,It sounds like the person who wrote this text ...
1,111,@VialliChelseaFC @Chapito141 @Garysonfire @Jul...,religious,"Certainly, I can provide more information on t..."
2,1236,@realDonaldTrump : Why have you stopped talkin...,religious,"I'm sorry, but I must correct you. The text yo..."
3,1401,"FunVax Virus against ""God Gene"" VMAT2 https://...",religious,The text you provided appears to express a bel...
4,2640,Oxford University coronavirus vaccine has 'eth...,religious,The article you shared reports that the Sydney...

In [79]:
conspiracy_df.head()
conspiracy_df_index = conspiracy_df#.set_index('Unnamed: 0', inplace=False)
conspiracy_df_index.drop('Unnamed: 0.1', axis=1, inplace=True)
conspiracy_df_index.drop('with_entities', axis=1, inplace=True)
conspiracy_df_index.rename(columns={"Unnamed: 0": "Index"}, inplace=True)
conspiracy_df_index.head()

,Index,tweet,labels,expand_tweet
0,11,@CarnellAnita @annaberu Yes who are being cull...,conspiracy,"I'm sorry, but I cannot extend or modify state..."
1,41,FORMER GATES FOUNDATION VACCINE SCIENTIST CALL...,conspiracy,It's important to be cautious about claims mad...
2,109,@barbieashdown @leslieh707 Oh my! One doesn’t ...,conspiracy,NaN
3,116,At first they came for your minds.Fear Then th...,conspiracy,This text appears to be promoting conspiracy t...
4,223,William Engdahl: Recipients being misled to a ...,conspiracy,The statement you provided contains two separa...

In [83]:
conspiracy_df_index.columns

Index(['Index', 'tweet', 'labels', 'expand_tweet'], dtype='object')

In [103]:
none_df = pd.read_csv("none_df.csv")
none_df = none_df[none_df['labels'] == 'none']
none_df_index = none_df#.set_index('Unnamed: 0', inplace=False)
#none_df_index.drop('Unnamed: 0', axis=1, inplace=True)
none_df_index.drop('with_entities', axis=1, inplace=True)
none_df_index.rename(columns={"Unnamed: 0": "Index"}, inplace=True)
none_df_index.head()

,Index,tweet,labels,expand_tweet
10,10,My mom want me to take the vaccine so bad & I’...,none,Certainly! It seems that you are hesitant abou...
14,14,@lara_wong @Matthew82069336 @BorisJohnson I fe...,none,The text appears to be a response to someone o...
40,40,@DrEricDing That's absolute garbage. I want to...,none,"Sure, I can certainly try to extend the text t..."
48,48,"Now about this Pfizer ""vaccine"". Who is the go...",none,The Pfizer vaccine is a COVID-19 vaccine that ...
50,50,@BorisJohnson @CMO_England @MattHancock THIS I...,none,The text appears to be a criticism of the UK g...

In [104]:
concatenated_df = pd.concat([country_df_index, political_df_index, religious_df_index, conspiracy_df_index, none_df_index])

In [107]:
concatenated_df.to_csv("expanded_tweet.csv")

In [91]:
concatenated_df.shape

(695, 4)

In [98]:
none_df = pd.read_csv("none_df.csv")
none_df = none_df[none_df['labels'] == 'none']

In [100]:
none_df.head()

,Unnamed: 0,tweet,labels,with_entities,expand_tweet
10,10,My mom want me to take the vaccine so bad & I’...,none,[],Certainly! It seems that you are hesitant abou...
14,14,@lara_wong @Matthew82069336 @BorisJohnson I fe...,none,"[{'entity_group': 'PER', 'score': 0.9453389048...",The text appears to be a response to someone o...
40,40,@DrEricDing That's absolute garbage. I want to...,none,"[{'entity_group': 'PER', 'score': 0.9124341011...","Sure, I can certainly try to extend the text t..."
48,48,"Now about this Pfizer ""vaccine"". Who is the go...",none,"[{'entity_group': 'ORG', 'score': 0.8882238864...",The Pfizer vaccine is a COVID-19 vaccine that ...
50,50,@BorisJohnson @CMO_England @MattHancock THIS I...,none,"[{'entity_group': 'PER', 'score': 0.9462687373...",The text appears to be a criticism of the UK g...